version: '3.8'

services:
  web:
    image: divinosys:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - pdv_data:/var/www/html
      - ./logs:/var/www/html/logs
      - ./uploads:/var/www/html/uploads
      - ./MVC/COMMON:/var/www/html/MVC/COMMON
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=122334Qw!!Conext
      - MYSQL_DATABASE=pdv_db
    networks:
      - pdv_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=122334Qw!!Conext
      - MYSQL_DATABASE=pdv_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - pdv_network

volumes:
  mysql_data:
  pdv_data:

networks:
  pdv_network:
    driver: overlay 